### ISSUE TITLE
Hackerone misinformation

### ISSUE THREAD

**Issue by i-tsaturov** [arkadiyt/bounty-targets#72]
Hi! There is an error in script that parsing companies from h1, that leads to some misinformation. In particular, the [raw data](https://github.com/arkadiyt/bounty-targets-data/blob/master/data/hackerone_data.json) collected by your script indicates that paypal does not pay bounty, however, just click on the link of their [program](https://hackerone.com/paypal) to make sure that this is not truth. The same about Airbnb

![image](https://user-images.githubusercontent.com/45243138/98401372-a1571280-2076-11eb-996b-7e0f56ef3245.png)

![image](https://user-images.githubusercontent.com/45243138/98401407-ad42d480-2076-11eb-9fd4-2f50a8eb4e0a.png)

**Comment by arkadiyt** [comment]
Thanks for flagging this - Hackerone changed some of their response fields which led to this error. It's been fixed in https://github.com/arkadiyt/bounty-targets/pull/73 and the bounty-targets-data commit https://github.com/arkadiyt/bounty-targets-data/commit/6597aef2b5fd1c438d35c0604790df27f0d1db39 has the correct `offers_bounties` flag for Paypal and several other programs.
